INSERT INTO books(title, description, coverimage, available)VALUES (
                                                                       'The Great Gatsby', 'Set in the 1920s, \"The Great Gatsby\" is a novel that vividly depicts the extravagance and decadence of the Jazz Age in America. It explores the life of Jay Gatsby, a mysterious millionaire, and his unrequited love for Daisy Buchanan. Through the lens of Nick Carraway, the story delves into themes of wealth, ambition, illusion, and the elusive American Dream.',
                                                                       'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/440px-The_Great_Gatsby_Cover_1925_Retouched.jpg',
                                                                       true
                                                                   );

INSERT INTO books(title, description, coverimage, available)VALUES ('To Kill a Mockingbird','Harper Lee''s masterpiece, ''To Kill a Mockingbird,'' ||
'' is a poignant exploration of racial prejudice and moral growth in the American South during the 1930s. The novel follows Scout Finch, her brother Jem, and their father Atticus as they navigate the complexities of a racially divided society. Through the lens of a child''s innocence, it addresses themes of injustice, empathy, and the power of compassion.','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/440px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg',true);

INSERT INTO books(title, description, coverimage, available)VALUES('Pride and Prejudice','Jane Austen''s "Pride and Prejudice" is a timeless tale of love ||
    ''tale of love, class, and societal expectations in early 19th-century England. It revolves around the headstrong Elizabeth Bennet and the enigmatic Mr. Darcy, whose initial pride and prejudice lead to misunderstandings and complications. This classic novel explores themes of manners, marriage, and the complexities of human relationships.','https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/PrideAndPrejudiceTitlePage.jpg/440px-PrideAndPrejudiceTitlePage.jpg',true);